### ISSUE TITLE
Getting java.lang.ClassNotFoundException: org.bouncycastle.crypto.Digest

### ISSUE THREAD

**Issue by taco2zday** [wavesplatform/WavesJ#1]
I'm just running the first usage example and getting the error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/crypto/Digest
	at com.hotcoins.bot.WavesJTest.main(WavesJTest.java:10)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.Digest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

Here is the example from the readme page that I ran:
---------------------------------------------------------
Create an account from a private key ('T' for testnet):

String seed = "health lazy lens fix dwarf salad breeze myself silly december endless rent faculty report beyond";
PrivateKeyAccount account = PrivateKeyAccount.fromSeed(seed, 0, Account.TESTNET);
byte[] publicKey = account.getPublicKey();
String address = account.getAddress();

**Comment by tubbynl** [comment]
Then the example is probably not mentioning the required dependencies on the classpath. In this case you need to add the bouncycastle crypto jar on the classpath

**Comment by petermz** [comment]
There are other dependencies as well, they all are listed in pom.xml.
