### ISSUE TITLE
com.fasterxml.jackson.databind.JsonMappingException

### ISSUE THREAD

**Issue by ady1981** [wavesplatform/WavesJ#55]
I updated the SpreadBot example with actual input values and it does not work.
```
import com.wavesplatform.wavesj.*;
import com.wavesplatform.wavesj.matcher.Order;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Timer;
import java.util.TimerTask;

public class SpreadBot {
    private final long maxOrderSize = 1 * Asset.MILLI; // in priceAsset
    private final double halfSpread = 0.01; // 1%
    private final long fee = 3 * Asset.MILLI; // in WAVES
    private final long period = 30000; // 1 min

    private final PrivateKeyAccount account;
    private final AssetPair market;
    private final Node node, matcher;
    private final String matcherKey;

    public static SpreadBot testnetInstance() throws IOException, URISyntaxException {
        return new SpreadBot(
                PrivateKeyAccount.fromPrivateKey("CNZvvKknunw4cktcsdKCvyrunbXYa42kC2W46D4kKsGE", Account.TESTNET),
                new AssetPair(Asset.WAVES, "DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn"),
                "https://matcher.testnet.wavesnodes.com/matcher",
                "https://nodes-testnet.wavesnodes.com",  'T');
    }

    private SpreadBot(PrivateKeyAccount account, AssetPair market, String matcherUrl, String nodeUrl, char chainId) throws IOException, URISyntaxException {
        this.account = account;
        this.market = market;
        this.node = new Node(nodeUrl, chainId);
        this.matcher = new Node(matcherUrl, chainId);
        this.matcherKey = matcher.getMatcherKey();
    }

    private void cancelOrder(String orderId) throws IOException, InterruptedException {
        String status = matcher.cancelOrder(account, market, orderId);
        System.out.printf("%s %s\n", status, orderId);
    }

    private String fileOrder(Order.Type type, long price, long amount) throws IOException, InterruptedException {
        long expiration = System.currentTimeMillis() + Math.max(period, 61000); // matcher requires expiration > 1 min in the future
        Order order = matcher.createOrder(account, matcherKey, market, type, price, amount, expiration, fee);
        System.out.printf("Filed order %s to %s %d at %d\n", order.getId(), type, amount, price);
        return order.getId().getBase58String();
    }

    private void round() throws IOException, InterruptedException {
        System.out.println();

        // Cancel all orders filed at our market
        for (Order order: matcher.getOrders(account, market)) {
            if (order.isActive()) {
                cancelOrder(order.getId().getBase58String());
            }
        }

        // Read order book
        OrderBook book = matcher.getOrderBook(market);
        if (book.getBids().size() <= 0) {
            System.out.println("There are no bids, skipping this round");
            return;
        }
        if (book.getAsks().size() <= 0) {
            System.out.println("There are no asks, skipping this round");
            return;
        }

        // Determine buy and sell prices
        long bestBid = book.getBids().get(0).getPrice();
        long bestAsk = book.getAsks().get(0).getPrice();
        System.out.printf("Spread %d : %d\n", bestBid, bestAsk);
        long meanPrice = (bestBid + bestAsk) / 2;
        long buyPrice = (long) (meanPrice * (1 - halfSpread));
        long sellPrice = (long) (meanPrice * (1 + halfSpread));

        // Find out how much we want to buy, and file an order
        long priceAssetAvail = node.getBalance(account.getAddress(), market.getPriceAsset()) - 2 * fee;
        if (priceAssetAvail > 0) {
            long buyOrderSize = Math.min(priceAssetAvail, maxOrderSize) * Asset.TOKEN / buyPrice;
            fileOrder(Order.Type.BUY, buyPrice, buyOrderSize);
        }

        // Same for sell order
        long amountAssetAvail = node.getBalance(account.getAddress(), market.getAmountAsset()) - 2 * fee;
        if (amountAssetAvail > 0) {
            long sellOrderSize = Math.min(amountAssetAvail, maxOrderSize * Asset.TOKEN / sellPrice);
            fileOrder(Order.Type.SELL, sellPrice, sellOrderSize);
        }
    }

    private class RoundTask extends TimerTask {
        @Override public void run() {
            try {
                round();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void run() {
        Timer t = new Timer();
        t.schedule(new RoundTask(), 0, period);
    }

    public static void main(String[] args) throws IOException, URISyntaxException {
        SpreadBot.testnetInstance().run();
    }
}

```
Exception:
```
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3077)
	at com.wavesplatform.wavesj.Node.parse(Node.java:685)
	at com.wavesplatform.wavesj.Node.getOrders(Node.java:607)
	at com.wavesplatform.wavesj.Node.getOrders(Node.java:593)
	at SpreadBot.round(SpreadBot.java:52)
	at SpreadBot.access$000(SpreadBot.java:9)
	at SpreadBot$RoundTask.run(SpreadBot.java:95)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745)
	at com.wavesplatform.wavesj.json.deser.OrderDeserializer.deserialize(OrderDeserializer.java:28)
	at com.wavesplatform.wavesj.json.deser.OrderDeserializer.deserialize(OrderDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	... 12 more

Process finished with exit code 130 (interrupted by signal 2: SIGINT)
```
Any ideas?

**Comment by br0x** [comment]
This library seems not supported anymore. Looks like your issue is the same as https://github.com/wavesplatform/WavesJ/issues/35

**Comment by msmolyakov** [comment]
WavesJ is maintained now. But since 1.0.0 version WavesJ supports only Waves Node API. Therefore, unfortunately, it doesn't support Matcher API.

To deal with the matcher, you can use [ccxt](https://docs.waves.exchange/en/ccxt/) library.
