### ISSUE TITLE
Http issue

### ISSUE THREAD

**Issue by Assassins719** [wavesplatform/WavesJ#9]
java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
        at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:955)
        at com.wavesplatform.wavesj.Node.<init>(Node.java:39)
        at com.passinhotv.android.TransferActivity.doTransfer(TransferActivity.java:202)
        at com.passinhotv.android.TransferActivity$2.onClick(TransferActivity.java:168)
        at android.view.View.performClick(View.java:5273)
        at android.view.View$PerformClick.run(View.java:21315)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5659)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by Assassins719** [comment]
How can I solve this issue? :-(

**Comment by Tolsi** [comment]
Have you apache http client library with some other version in your project? Or you try to use it on android?
